server:
  port: 8001
  
spring:
  cloud:
    config:
      fail-fast: true
     retry:
       max-attempts: 10000
       max-interval: 1000
    consul:
      discovery:
        instanceId: ms-service-a
        health-check-interval: 5s
service:
  b:
    url: http://ms-service-b/service/b